### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by iAmInActions** [gameblabla/mccraft#2]
Hi,
Ive tried to compile this but it does not want to work on my 64 bit pc. it worked fine on my netbook but when i run `gcc main.c -o mccraft` what worked on the netbook on my pc, i get this error:
```
/usr/bin/ld: /tmp/ccWwgG8K.o: in function `main':
main.c:(.text+0xb40): undefined reference to `cos'
/usr/bin/ld: main.c:(.text+0xb72): undefined reference to `cos'
/usr/bin/ld: main.c:(.text+0xba4): undefined reference to `sin'
/usr/bin/ld: main.c:(.text+0xbd6): undefined reference to `sin'
/usr/bin/ld: main.c:(.text+0xdaa): undefined reference to `sqrt'
collect2: error: ld returned 1 exit status
```

my gcc version is 11.2.0-7ubuntu2 from the ubuntu impish repo.

**Comment by gameblabla** [comment]
You are supposed to do so with the Makefile as it adds the "-lm" library that should be linked against.
