### ISSUE TITLE
License

### ISSUE THREAD

**Issue by theoparis** [gameblabla/mccraft#3]
Hi there. I know this was originally from a forum post but there is no license file. I wanted to fork this repository since I have gotten the SDL 1.2 renderer to work properly on my linux machine but I wasn't sure if it was ok to fork it under a BSD 0 or 2 clause license...

**Comment by gameblabla** [comment]
Sorry but i'm not in position to tell you to go ahead and relicense it, he merely posted his code on a forum thread (without any license).
You will have to ask TheGhastModding at https://www.avrfreaks.net/s/topic/a5C3l000000UZVyEAO/t150312
However there's no guarantee he will answer you back
